# Generated by Django 6.0.3 on 2026-04-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_entree_stock',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'entrée en stock"),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_peremption',
            field=models.DateField(blank=True, null=True, verbose_name='Date de péremption'),
        ),
    ]
